siteTitle="ezbake"
baseColor = "#7496c2"
linkPrefix = "/ezbake"
docPages = [
  "/docs/",
  "/docs/getting-started/",
  "/docs/how-ezbake-works/",
  "/docs/ezbake-commands/",
  "/docs/ezbake-a-project/",
  "/docs/setup-ezbake-folder/",
  "/docs/distribute-to-developers/",
  "/docs/examples/"
]
